[advisories]
db-path = "~/.cargo/advisory-db"
db-url = "https://github.com/rustsec/advisory-db"
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    #"RUSTSEC-0000-0000",
]

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
]
deny = [
    #"Nokia",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    { allow = ["BSD-3-Clause"], name = "argh"},
    { allow = ["BSD-3-Clause"], name = "argh_derive"},
    { allow = ["BSD-3-Clause"], name = "argh_shared"},
]

[licenses.private]
ignore = false
registries = [
    #"https://sekretz.com/registry
]

[bans]
multiple-versions = "warn"
wildcards = "warn"
highlight = "all"
allow = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
deny = [
    #{ name = "ansi_term", version = "=0.11.0" },
]
skip = [
    { name = "ansi_term", version = "=0.11.0" },
]
skip-tree = [
    #{ name = "ansi_term", version = "=0.11.0", depth = 20 },
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
